-- --------------------------------------------------------
-- Hôte:                         localhost
-- Version du serveur:           5.7.33 - MySQL Community Server (GPL)
-- SE du serveur:                Win64
-- HeidiSQL Version:             11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Listage de la structure de la base pour php_projet_individu
DROP DATABASE IF EXISTS `php_projet_individu`;
CREATE DATABASE IF NOT EXISTS `php_projet_individu` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `php_projet_individu`;

-- Listage de la structure de la table php_projet_individu. products
DROP TABLE IF EXISTS `products`;
CREATE TABLE IF NOT EXISTS `products` (
  `id` int(4) NOT NULL AUTO_INCREMENT,
  `name` varchar(500) NOT NULL,
  `image` varchar(500) DEFAULT NULL COMMENT 'string of link to its image',
  `genre` varchar(100) DEFAULT NULL COMMENT 'value: male or female',
  `price` float DEFAULT '0',
  `quantity` int(6) DEFAULT '0',
  `description` text,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8;

-- Listage des données de la table php_projet_individu.products : ~26 rows (environ)
/*!40000 ALTER TABLE `products` DISABLE KEYS */;
REPLACE INTO `products` (`id`, `name`, `image`, `genre`, `price`, `quantity`, `description`, `created_at`) VALUES
	(1, 'CHLOE ABSOLU DE PARFUM 75ML', 'Chloe-Absolu.webp', 'female', 120, 10, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-01-10 14:16:57'),
	(2, '4711 ACQUA COLONIA BLOOD ORANGE & BASIL EAU DE COLOGNE 170ML', 'Acqua-Colonia-Blood-Orange-and-Basil.webp', 'female', 59.99, 20, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-10-09 14:18:13'),
	(3, '4711 ACQUA COLONIA LYCHEE & WHITE MINT EAU DE COLOGNE 170ML', '4711-Acqua-Colonia-Lychee.webp', 'female', 49.99, 0, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-09-06 14:22:20'),
	(4, '4711 REMIX GRAPEFRUIT EAU DE COLOGNE 100ML', '4711-Remix-Grapefruit.webp', 'female', 25, 5, '<br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-10-26 14:23:33'),
	(5, '4711 REMIX GRAPEFRUIT EAU DE COLOGNE 100ML', '4711-Remix-Grapefruit.webp', 'female', 25, 5, '<br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-10-06 14:23:33'),
	(6, '4711 REMIX GRAPEFRUIT EAU DE COLOGNE 100ML', '4711-Remix-Grapefruit.webp', 'female', 25, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-05-16 14:23:33'),
	(7, '4711 REMIX GRAPEFRUIT EAU DE COLOGNE 100ML', '4711-Remix-Grapefruit.webp', 'female', 25, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-04-16 14:23:33'),
	(8, '4711 REMIX GRAPEFRUIT EAU DE COLOGNE 100ML', '4711-Remix-Grapefruit.webp', 'female', 25, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-03-16 14:23:33'),
	(9, '4711 REMIX GRAPEFRUIT EAU DE COLOGNE 100ML', '4711-Remix-Grapefruit.webp', 'female', 25, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-02-16 14:23:33'),
	(10, '4711 REMIX GRAPEFRUIT EAU DE COLOGNE 100ML', '4711-Remix-Grapefruit.webp', 'female', 25, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-11-16 14:23:33'),
	(11, 'AZZARO CHROME EAU DE TOILETTE 200ML', 'Azzaro-Chrome-Eau-De-Toilette-200ml.webp', 'male', 89.95, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-07-16 14:23:33'),
	(12, 'BURBERRY BRIT FOR HIM EAU DE TOILETTE 100ML', 'Burberry-Brit-For-Him.webp', 'male', 69.95, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2020-09-16 14:23:33'),
	(13, 'BALDESSARINI AMBRÉ EAU FRAICHE EAU DE TOILETTE 90ML', 'Baldessarini-Ambre.webp', 'male', 49, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-10-16 14:23:33'),
	(14, 'AZZARO WANTED EAU DE TOILETTE 100ML', 'Azzaro-Wanted-Eau-De-Toilette.webp', 'male', 79.99, 10, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-01-16 14:23:33'),
	(15, 'DAVID BECKHAM INFINITE AQUA EAU DE PARFUM 100ML', 'David-Beckham-Infinite.webp', 'male', 59, 7, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-11-01 14:23:33'),
	(16, 'DAVID BECKHAM AROMATIC GREENS EAU DE PARFUM 100ML', 'David-Beckham-Aromatic-Greens.webp', 'male', 59, 30, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-11-10 14:23:33'),
	(17, 'AZZARO CHROME EAU DE TOILETTE 200ML', 'Azzaro-Chrome-Eau-De-Toilette-200ml.webp', 'male', 89.95, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-07-16 14:23:33'),
	(18, 'BALDESSARINI AMBRÉ EAU FRAICHE EAU DE TOILETTE 90ML', 'Baldessarini-Ambre.webp', 'male', 49, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-10-16 14:23:33'),
	(19, 'BURBERRY BRIT FOR HIM EAU DE TOILETTE 100ML', 'Burberry-Brit-For-Him.webp', 'male', 69.95, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2020-09-16 14:23:33'),
	(20, 'AZZARO WANTED EAU DE TOILETTE 100ML', 'Azzaro-Wanted-Eau-De-Toilette.webp', 'male', 79.99, 10, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-01-16 14:23:33'),
	(21, 'DAVID BECKHAM INFINITE AQUA EAU DE PARFUM 100ML', 'David-Beckham-Infinite.webp', 'male', 59, 7, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-11-01 14:23:33'),
	(22, 'DAVID BECKHAM AROMATIC GREENS EAU DE PARFUM 100ML', 'David-Beckham-Aromatic-Greens.webp', 'male', 59, 30, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-11-10 14:23:33'),
	(23, 'CHLOE ABSOLU DE PARFUM 75ML', 'Chloe-Absolu.webp', 'female', 120, 10, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-01-10 14:16:57'),
	(24, 'BALDESSARINI AMBRÉ EAU FRAICHE EAU DE TOILETTE 90ML', 'Baldessarini-Ambre.webp', 'male', 49, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-10-16 14:23:33'),
	(25, 'BURBERRY BRIT FOR HIM EAU DE TOILETTE 100ML', 'Burberry-Brit-For-Him.webp', 'male', 69.95, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2020-09-16 14:23:33'),
	(26, 'AZZARO CHROME EAU DE TOILETTE 200ML', 'Azzaro-Chrome-Eau-De-Toilette-200ml.webp', 'male', 89.95, 5, '<br> <br>\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. <br>\r\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. <br> \r\nCras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi. <br> \r\nProin porttitor, orci nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit amet erat. <br>\r\nDuis semper. Duis arcu massa, scelerisque vitae, consequat in, pretium a, enim. Pellentesque congue. <br>\r\nUt in risus volutpat libero pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo in pede. \r\n<br> <br>\r\nTop notes: Praesent blandit odio eu enim. Pellentesque sed dui ut augue blandit sodales. <br>\r\nHeart notes: Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nibh. <br>\r\nBase notes: Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales hendrerit. <br>', '2022-07-16 14:23:33');
/*!40000 ALTER TABLE `products` ENABLE KEYS */;

-- Listage de la structure de la table php_projet_individu. users
DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(4) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(500) DEFAULT NULL,
  `password` varchar(500) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

-- Listage des données de la table php_projet_individu.users : ~11 rows (environ)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
REPLACE INTO `users` (`id`, `name`, `email`, `password`, `created_at`) VALUES
	(1, 'hung', 'vtrhung@yahoo.com', '$2y$10$bxVfvONOjHshN2Odyw0IGO4uYykNWJAIpAKj1WAmZSueDgh.Fivmi', NULL),
	(2, 'hung', 'test@yahoo.com', '$2y$10$pKyS/U0wk9uZaCbRQrt9dOyJw7GsBb/POArzN1ZDXDG6LHa.Yqbti', NULL),
	(3, 'hung', 'test2@yahoo.com', '$2y$10$qch3W6yvXDuWnyFoYGTkue5c68jePsYuGY2QK8hfuTLSvua3snWf.', '2022-11-14 00:00:00'),
	(4, 'hung', 'test3@yahoo.com', '$2y$10$Hl6mqt4bPoBVUtAu64F3hO7x/OqvVSq98EcneD6rAAdgKFCOLZzXy', '2022-11-14 00:00:00'),
	(5, 'hung', 'test5@gmail.com', '$2y$10$SFuMmXD0pyQos2zTznWSGekFWNbdnDqXnrO4axSfYYbi6Gn.DW..a', '2022-11-14 00:00:00'),
	(6, 'hung', 'test6@gmail.com', '$2y$10$NCX0MWPHGQ7UcTNrYh5DneiqEfIAwH/Db9Y5dDk7PhcGivwsG8TVK', '2022-11-14 00:00:00'),
	(7, 'hung', 'test7@yahoo.com', '$2y$10$7OAbb3MOGFd7OHoMBiJLceRV1llqAhgLF2YIYu5SWA2couhAR/5/a', '2022-11-14 00:00:00'),
	(8, 'hung', 'test8@yahoo.com', '$2y$10$2AUsdt8gs6p4hau8rpIwweup99GaJlkfepdi/WiK3yPW9.o/Dd6H.', '2022-11-14 03:11:30'),
	(9, 'hung', 'test8@gmail.com', '$2y$10$o9227IY7w5AYKxtUfGt48OWGo6hWbeQXp1tYwKf22a79qoj0lflG.', '2022-11-14 15:38:55'),
	(10, 'hung', 'test9@gmail.com', '$2y$10$PaYfzUaOtrlI7mcfamYt6.sB2PTuFebRctKrV.XTyVNmjLAor6Q4G', '2022-11-14 16:40:47'),
	(11, 'hung', 'test9@yahoo.com', '$2y$10$mF4oZqoazmfszt5sz4mIYe5G1G.qy1f03R16dosRx0Dm8cknlXFpi', '2022-11-15 08:53:09');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
